// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: pb/comm_v4.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToDevice struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ToDevice_Request
	Message       isToDevice_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToDevice) Reset() {
	*x = ToDevice{}
	mi := &file_pb_comm_v4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDevice) ProtoMessage() {}

func (x *ToDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pb_comm_v4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDevice.ProtoReflect.Descriptor instead.
func (*ToDevice) Descriptor() ([]byte, []int) {
	return file_pb_comm_v4_proto_rawDescGZIP(), []int{0}
}

func (x *ToDevice) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ToDevice) GetMessage() isToDevice_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ToDevice) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Message.(*ToDevice_Request); ok {
			return x.Request
		}
	}
	return nil
}

type isToDevice_Message interface {
	isToDevice_Message()
}

type ToDevice_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

func (*ToDevice_Request) isToDevice_Message() {}

type FromDevice struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*FromDevice_Response
	Message       isFromDevice_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromDevice) Reset() {
	*x = FromDevice{}
	mi := &file_pb_comm_v4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromDevice) ProtoMessage() {}

func (x *FromDevice) ProtoReflect() protoreflect.Message {
	mi := &file_pb_comm_v4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromDevice.ProtoReflect.Descriptor instead.
func (*FromDevice) Descriptor() ([]byte, []int) {
	return file_pb_comm_v4_proto_rawDescGZIP(), []int{1}
}

func (x *FromDevice) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FromDevice) GetMessage() isFromDevice_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *FromDevice) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Message.(*FromDevice_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isFromDevice_Message interface {
	isFromDevice_Message()
}

type FromDevice_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

func (*FromDevice_Response) isFromDevice_Message() {}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        uint32                 `protobuf:"varint,1,opt,name=method,proto3" json:"method,omitempty"` // 0:GET, 1:POST, 2:PUT, 3:DELETE
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pb_comm_v4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_comm_v4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pb_comm_v4_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetMethod() uint32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pb_comm_v4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_comm_v4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pb_comm_v4_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pb_comm_v4_proto protoreflect.FileDescriptor

const file_pb_comm_v4_proto_rawDesc = "" +
	"\n" +
	"\x10pb/comm_v4.proto\x12\x10ubiquiti.comm.v4\"k\n" +
	"\bToDevice\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x19.ubiquiti.comm.v4.RequestH\x00R\arequestB\t\n" +
	"\amessage\"p\n" +
	"\n" +
	"FromDevice\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x128\n" +
	"\bresponse\x18\x02 \x01(\v2\x1a.ubiquiti.comm.v4.ResponseH\x00R\bresponseB\t\n" +
	"\amessage\"\xcd\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\rR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.ubiquiti.comm.v4.Request.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_comm_v4_proto_rawDescOnce sync.Once
	file_pb_comm_v4_proto_rawDescData []byte
)

func file_pb_comm_v4_proto_rawDescGZIP() []byte {
	file_pb_comm_v4_proto_rawDescOnce.Do(func() {
		file_pb_comm_v4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_comm_v4_proto_rawDesc), len(file_pb_comm_v4_proto_rawDesc)))
	})
	return file_pb_comm_v4_proto_rawDescData
}

var file_pb_comm_v4_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_comm_v4_proto_goTypes = []any{
	(*ToDevice)(nil),   // 0: ubiquiti.comm.v4.ToDevice
	(*FromDevice)(nil), // 1: ubiquiti.comm.v4.FromDevice
	(*Request)(nil),    // 2: ubiquiti.comm.v4.Request
	(*Response)(nil),   // 3: ubiquiti.comm.v4.Response
	nil,                // 4: ubiquiti.comm.v4.Request.HeadersEntry
}
var file_pb_comm_v4_proto_depIdxs = []int32{
	2, // 0: ubiquiti.comm.v4.ToDevice.request:type_name -> ubiquiti.comm.v4.Request
	3, // 1: ubiquiti.comm.v4.FromDevice.response:type_name -> ubiquiti.comm.v4.Response
	4, // 2: ubiquiti.comm.v4.Request.headers:type_name -> ubiquiti.comm.v4.Request.HeadersEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_comm_v4_proto_init() }
func file_pb_comm_v4_proto_init() {
	if File_pb_comm_v4_proto != nil {
		return
	}
	file_pb_comm_v4_proto_msgTypes[0].OneofWrappers = []any{
		(*ToDevice_Request)(nil),
	}
	file_pb_comm_v4_proto_msgTypes[1].OneofWrappers = []any{
		(*FromDevice_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_comm_v4_proto_rawDesc), len(file_pb_comm_v4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_comm_v4_proto_goTypes,
		DependencyIndexes: file_pb_comm_v4_proto_depIdxs,
		MessageInfos:      file_pb_comm_v4_proto_msgTypes,
	}.Build()
	File_pb_comm_v4_proto = out.File
	file_pb_comm_v4_proto_goTypes = nil
	file_pb_comm_v4_proto_depIdxs = nil
}
